import { CheckCircle } from '@mui/icons-material'
import Head from 'next/head'
import Image from 'next/image'
import CheckIn from '../components/AllCheckIn/CheckIn'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Anvil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CheckIn />
    </div>
  )
}
